//
// Created by DemonLee on 5/28/22.
//

#ifndef NETWORK_PROGRAMMING_IN_ACTION_GENERAL_H
#define NETWORK_PROGRAMMING_IN_ACTION_GENERAL_H

#define LISTEN_QUEUE 1024
#define BUFFER_SIZE 1024
#define MAX_LINE 4096

#define UNKNOWN_ERROR 9999

#endif //NETWORK_PROGRAMMING_IN_ACTION_GENERAL_H
